/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ittimfn.sample.juniversalchardet;

public class App {
    public void exec(String[] args) {
        
    }

    public static void main(String[] args) {
        new App().exec(args);
    }
}
